//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 04:09:17 PM CET 
//


package minibase.catalog.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for foreignKey complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="foreignKey"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sourceColumns" type="{http://minibase/catalog/v1}columnRefs"/&gt;
 *         &lt;element name="targetColumns" type="{http://minibase/catalog/v1}columnOverTableRefs"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "foreignKey", propOrder = {
        "sourceColumns",
        "targetColumns"
})
public class ForeignKey {

    @XmlElement(required = true)
    protected ColumnRefs sourceColumns;
    @XmlElement(required = true)
    protected ColumnOverTableRefs targetColumns;

    /**
     * Gets the value of the sourceColumns property.
     *
     * @return possible object is
     * {@link ColumnRefs }
     */
    public ColumnRefs getSourceColumns() {
        return sourceColumns;
    }

    /**
     * Sets the value of the sourceColumns property.
     *
     * @param value allowed object is
     *              {@link ColumnRefs }
     */
    public void setSourceColumns(ColumnRefs value) {
        this.sourceColumns = value;
    }

    /**
     * Gets the value of the targetColumns property.
     *
     * @return possible object is
     * {@link ColumnOverTableRefs }
     */
    public ColumnOverTableRefs getTargetColumns() {
        return targetColumns;
    }

    /**
     * Sets the value of the targetColumns property.
     *
     * @param value allowed object is
     *              {@link ColumnOverTableRefs }
     */
    public void setTargetColumns(ColumnOverTableRefs value) {
        this.targetColumns = value;
    }

}
