//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 04:09:17 PM CET 
//


package minibase.catalog.v1;

import jakarta.xml.bind.annotation.*;

/**
 * <p>Java class for index complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="index"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pages" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cardinality" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="keyColumns" type="{http://minibase/catalog/v1}columnRefs"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="btree"/&gt;
 *             &lt;enumeration value="hash"/&gt;
 *             &lt;enumeration value="bitmap"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="clustered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "index", propOrder = {
        "pages",
        "cardinality",
        "keyColumns"
})
public class Index {

    protected int pages;
    protected int cardinality;
    @XmlElement(required = true)
    protected ColumnRefs keyColumns;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "clustered")
    protected Boolean clustered;

    /**
     * Gets the value of the pages property.
     */
    public int getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     */
    public void setPages(int value) {
        this.pages = value;
    }

    /**
     * Gets the value of the cardinality property.
     */
    public int getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     */
    public void setCardinality(int value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the keyColumns property.
     *
     * @return possible object is
     * {@link ColumnRefs }
     */
    public ColumnRefs getKeyColumns() {
        return keyColumns;
    }

    /**
     * Sets the value of the keyColumns property.
     *
     * @param value allowed object is
     *              {@link ColumnRefs }
     */
    public void setKeyColumns(ColumnRefs value) {
        this.keyColumns = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the clustered property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isClustered() {
        if (clustered == null) {
            return false;
        } else {
            return clustered;
        }
    }

    /**
     * Sets the value of the clustered property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setClustered(Boolean value) {
        this.clustered = value;
    }

}
