//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 04:09:17 PM CET 
//


package minibase.catalog.v1;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the minibase.catalog.v1 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: minibase.catalog.v1
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemCatalog }
     */
    public SystemCatalog createSystemCatalog() {
        return new SystemCatalog();
    }

    /**
     * Create an instance of {@link ColumnOverTableRefs }
     */
    public ColumnOverTableRefs createColumnOverTableRefs() {
        return new ColumnOverTableRefs();
    }

    /**
     * Create an instance of {@link ColumnRefs }
     */
    public ColumnRefs createColumnRefs() {
        return new ColumnRefs();
    }

    /**
     * Create an instance of {@link Table }
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link SystemCatalog.Tables }
     */
    public SystemCatalog.Tables createSystemCatalogTables() {
        return new SystemCatalog.Tables();
    }

    /**
     * Create an instance of {@link minibase.catalog.v1.Column }
     */
    public minibase.catalog.v1.Column createColumn() {
        return new minibase.catalog.v1.Column();
    }

    /**
     * Create an instance of {@link Index }
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link ForeignKey }
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link PrimaryKey }
     */
    public PrimaryKey createPrimaryKey() {
        return new PrimaryKey();
    }

    /**
     * Create an instance of {@link ColumnOverTableRefs.Column }
     */
    public ColumnOverTableRefs.Column createColumnOverTableRefsColumn() {
        return new ColumnOverTableRefs.Column();
    }

    /**
     * Create an instance of {@link ColumnRefs.Column }
     */
    public ColumnRefs.Column createColumnRefsColumn() {
        return new ColumnRefs.Column();
    }

    /**
     * Create an instance of {@link Table.Columns }
     */
    public Table.Columns createTableColumns() {
        return new Table.Columns();
    }

    /**
     * Create an instance of {@link Table.Indexes }
     */
    public Table.Indexes createTableIndexes() {
        return new Table.Indexes();
    }

}
