//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 04:09:17 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://minibase/catalog/v1", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package minibase.catalog.v1;
