//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 04:09:17 PM CET 
//


package minibase.catalog.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for primaryKey complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="primaryKey"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="columns" type="{http://minibase/catalog/v1}columnRefs"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "primaryKey", propOrder = {
        "columns"
})
public class PrimaryKey {

    @XmlElement(required = true)
    protected ColumnRefs columns;

    /**
     * Gets the value of the columns property.
     *
     * @return possible object is
     * {@link ColumnRefs }
     */
    public ColumnRefs getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     *
     * @param value allowed object is
     *              {@link ColumnRefs }
     */
    public void setColumns(ColumnRefs value) {
        this.columns = value;
    }

}
