/* Generated By:JavaCC: Do not edit this line. QueryExpressionParserTreeConstants.java Version 6.1_2 */
package minibase.query.optimizer.parser;

public interface QueryExpressionParserTreeConstants {
    public int JJTEXPRESSION = 0;
    public int JJTOPERATOR = 1;
    public int JJTVOID = 2;


    public String[] jjtNodeName = {
            "Expression",
            "Operator",
            "void",
    };
}
/* JavaCC - OriginalChecksum=5d9096ef7a81566cdd10f87e439f5496 (do not edit this line) */
